name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven and Quarkus 2.1.1 (Expect no errors)
        run: mvn -B clean package -P2.1.1 --file pom.xml
      - name: Build with Maven and Quarkus 2.1.2 (Expect errors)
        run: mvn -B clean package -P2.1.2 --file pom.xml

